import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { routes } from "../config/routes.mjs";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const notice = "# Generated by scripts/generate-routing.mjs; edit config/routes.mjs.\n";
const caddyGlobal = `{
\tservers {
\t\ttrusted_proxies static private_ranges
\t\tclient_ip_headers CF-Connecting-IP X-Forwarded-For
\t\ttrusted_proxies_strict
\t}
}`;
const caddyfile = `${notice}${caddyGlobal}\n\n${routes.map((route) => route.caddy).join("\n\n")}\n`;
const ingress = routes
  .map((route) => {
    const port = route.tunnelProtocol === "https" ? 443 : 80;
    const origin = route.tunnelProtocol === "https"
      ? `\n    originRequest:\n      originServerName: ${route.hostname}`
      : "";
    return `  - hostname: ${route.hostname}\n    service: ${route.tunnelProtocol}://edge:${port}${origin}`;
  })
  .join("\n");
const cloudflared = `${notice}tunnel: <tunnel-id>\ncredentials-file: /etc/cloudflared/credentials.json\n\ningress:\n${ingress}\n  - service: http_status:404\n`;
const outputs = new Map([
  [join(root, "edge/Caddyfile"), caddyfile],
  [join(root, "env/cloudflared.config.yml.example"), cloudflared],
]);

if (process.argv.includes("--check")) {
  let stale = false;
  for (const [path, content] of outputs) {
    if (readFileSync(path, "utf8") !== content) {
      console.error(`${path} is stale; run bun run generate:routing.`);
      stale = true;
    }
  }
  process.exit(stale ? 1 : 0);
}

for (const [path, content] of outputs) writeFileSync(path, content);
console.log("Generated Caddy and Cloudflare Tunnel routing.");
